from __future__ import annotations

COUNTRY_REGION_MAP: dict[str, str] = {
    "United Kingdom": "Europe",
    "United States": "North America",
    "Canada": "North America",
    "Mexico": "North America",
    "France": "Europe",
    "Germany": "Europe",
    "Italy": "Europe",
    "Spain": "Europe",
    "Monaco": "Europe",
    "Belgium": "Europe",
    "Netherlands": "Europe",
    "Austria": "Europe",
    "Hungary": "Europe",
    "Azerbaijan": "Europe/Asia",
    "Russia": "Europe/Asia",
    "Ukraine": "Europe",
    "Poland": "Europe",
    "European Union": "Europe",
    "Turkey": "Europe/Asia",
    "Lebanon": "Middle East",
    "Iran": "Middle East",
    "Saudi Arabia": "Middle East",
    "United Arab Emirates": "Middle East",
    "Qatar": "Middle East",
    "Bahrain": "Middle East",
    "Japan": "Asia",
    "China": "Asia",
    "India": "Asia",
    "South Korea": "Asia",
    "North Korea": "Asia",
    "Taiwan": "Asia",
    "Singapore": "Asia",
    "Australia": "Oceania",
    "Brazil": "South America",
}

COUNTRY_KEYWORDS: dict[str, list[str]] = {
    "United Kingdom": ["united kingdom", "uk", "britain", "british", "england", "london", "westminster", "downing street", "starmer", "sunak", "silverstone"],
    "United States": [
        "united states", "u.s.", "us ", "america", "american", "washington", "white house", "trump", "biden",
        "wwdc", "apple", "openai", "meta", "anthropic", "google", "microsoft", "tesla", "xai",
        "las vegas", "miami", "austin",
    ],
    "Canada": ["canada", "ottawa", "montreal", "toronto"],
    "Mexico": ["mexico", "mexico city"],
    "France": ["france", "paris"],
    "Germany": ["germany", "berlin"],
    "Italy": ["italy", "rome", "monza", "imola", "ferrari"],
    "Spain": ["spain", "madrid", "barcelona"],
    "Monaco": ["monaco", "monte carlo"],
    "Belgium": ["belgium", "spa-francorchamps", "spa grand prix", "spa"],
    "Netherlands": ["netherlands", "dutch", "zandvoort", "amsterdam"],
    "Austria": ["austria", "spielberg", "vienna", "red bull ring"],
    "Hungary": ["hungary", "budapest", "hungaroring"],
    "Azerbaijan": ["azerbaijan", "baku"],
    "Russia": ["russia", "moscow", "kremlin"],
    "Ukraine": ["ukraine", "kyiv", "kiev"],
    "Poland": ["poland", "warsaw"],
    "European Union": ["eu ", "european union", "brussels", "european commission", "nato"],
    "Turkey": ["turkey", "ankara", "istanbul"],
    "Lebanon": ["lebanon", "beirut", "hezbollah"],
    "Iran": ["iran", "tehran", "hormuz", "strait of hormuz"],
    "Saudi Arabia": ["saudi arabia", "riyadh", "jeddah"],
    "United Arab Emirates": ["united arab emirates", "uae", "abu dhabi", "dubai"],
    "Qatar": ["qatar", "doha"],
    "Bahrain": ["bahrain", "sakhir"],
    "Japan": ["japan", "tokyo", "suzuka", "nintendo", "sony"],
    "China": ["china", "beijing", "shanghai"],
    "India": ["india", "delhi", "new delhi"],
    "South Korea": ["south korea", "korea", "seoul", "bts", "samsung", "hyundai"],
    "North Korea": ["north korea", "pyongyang"],
    "Taiwan": ["taiwan", "taipei", "tsmc"],
    "Singapore": ["singapore"],
    "Australia": ["australia", "melbourne", "sydney"],
    "Brazil": ["brazil", "brasil", "interlagos", "sao paulo"],
}

NON_GEOGRAPHIC_KEYWORDS = {
    "space",
    "astronomy",
    "cosmos",
    "deep-space",
    "astrophysics",
    "nasa mission",
}

GLOBAL_ONLY_KEYWORDS = {
    "world tour",
    "global markets",
    "global economy",
}

SPORTS_KEYWORDS = {
    "f1",
    "formula 1",
    "grand prix",
    "qualifying",
    "race weekend",
    "paddock",
    "driver market",
    "football",
    "tennis",
    "cricket",
}

F1_VENUE_COUNTRY = {
    "silverstone": "United Kingdom",
    "monaco": "Monaco",
    "monza": "Italy",
    "imola": "Italy",
    "spa": "Belgium",
    "spa-francorchamps": "Belgium",
    "suzuka": "Japan",
    "bahrain": "Bahrain",
    "jeddah": "Saudi Arabia",
    "melbourne": "Australia",
    "shanghai": "China",
    "miami": "United States",
    "austin": "United States",
    "las vegas": "United States",
    "singapore": "Singapore",
    "zandvoort": "Netherlands",
    "spielberg": "Austria",
    "budapest": "Hungary",
    "baku": "Azerbaijan",
    "doha": "Qatar",
    "abu dhabi": "United Arab Emirates",
    "montreal": "Canada",
    "mexico city": "Mexico",
    "interlagos": "Brazil",
    "barcelona": "Spain",
}

DEFAULT_REGION_OPTIONS = ["United Kingdom", "Global"]
